site_name: Troika
site_author: Jason Johnston
repo_url: https://github.com/protectwise/troika
plugins:
  # - monorepo
  # - include-markdown
  - search
theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.b64 #not working???
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Overview: index.md
  - Getting Started:
      - getting-started/setup.md
      - getting-started/examples.md
  - Core Concepts:
      - troika-core/facades.md
      - troika-core/scene-descriptors.md
      - troika-core/interactivity-and-events.md
      - troika-core/animations-and-transitions.md
  - Troika 3D:
      - troika-3d/index.md
      - troika-3d/scenes.md
      - troika-3d/objects.md
      - troika-3d/interactivity-and-events.md
      - troika-3d/performance.md
      - troika-3d/instancing.md
      - troika-3d/html-overlays.md
      - troika-3d/text.md
      - troika-3d-ui/index.md
  - Three.js Tools:
      - Troika 3D Text: troika-three-text/index.md
      - Derived Materials: troika-three-utils/createDerivedMaterial.md
      - BezierMesh: troika-three-utils/BezierMesh.md
      - InstancedUniformsMesh: three-instanced-uniforms-mesh/index.md
  - Troika 2D:
      - troika-2d/index.md
      - troika-2d/objects.md
      - troika-2d/html-overlays.md




#  - Troika Core: '!include ./packages/troika-core/mkdocs.yml'
#  - Troika 3D Text: '../packages/troika-three-text/README.md' #'!include ./packages/troika-three-text/mkdocs.yml'
